#
# Stage 1: building GVSOC & PULP GCC on non-Linux platforms
#
FROM ubuntu:24.04 AS builder
RUN apt update && apt upgrade -y
ENV TZ=Europe/Rome

# Install locales to generate en_US.UTF-8
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y locales && \
    locale-gen en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8 && \
    rm -rf /var/lib/apt/lists/*

# basic tools
RUN DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends --allow-unauthenticated \
vim \
emacs

# install deps (gvsoc)
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        build-essential \
        git \
        doxygen \
        python3-pip \
        libsdl2-dev \
        curl \
        cmake \
        gtkwave \
        libsndfile1-dev \
        rsync \
        autoconf \
        automake \
        texinfo \
        libtool \
        pkg-config \
        libsdl2-ttf-dev \
        wget \
        python3-sphinx \
    && rm -rf /var/lib/apt/lists/*

# # Set the locale, because Vivado crashes otherwise
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

WORKDIR /main_folder

# Clone GVSOC
RUN git clone https://github.com/gvsoc/gvsoc.git gvsoc-01
RUN cd gvsoc-01 && \
git submodule update --init --recursive -j 8

# INSTALL PYTHON deps
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --allow-unauthenticated python3 python3-venv
RUN python3 -m venv gvsoc-venv
ENV PATH="/main_folder/gvsoc-venv/bin:$PATH"
RUN cd gvsoc-01; pip install -r core/requirements.txt
RUN cd gvsoc-01; pip install -r gapy/requirements.txt
RUN pip install torch
RUN pip install torch onnx mako
RUN pip install argcomplete
RUN pip install jsonref
RUN pip install jsonschema
#RUN pip install ortools
#RUN pip install pydantic

# INSTALL GVSoC
RUN cd gvsoc-01; make all TARGETS=spatz
ENV PATH="/main_folder/gvsoc-01/install/bin:$PATH"

# Install GCC Deps
RUN DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends --allow-unauthenticated \
autotools-dev \
libmpc-dev \
libmpfr-dev \
libgmp-dev \
gawk \
bison \
flex \
gperf \
patchutils \
bc \
zlib1g-dev

# Install GCC 
RUN git clone --recursive https://github.com/pulp-platform/pulp-riscv-gnu-toolchain
RUN cd pulp-riscv-gnu-toolchain; ./configure --prefix=/main_folder/riscv-gcc --with-arch=rv32imc --with-cmodel=medlow --enable-multilib
RUN cd pulp-riscv-gnu-toolchain; make

# Install LLVM

# Install OBPMark-ML Deps

## prepare environment
ENV PULP_RISCV_GCC_TOOLCHAIN=/main_folder/riscv-gcc
ENV PATH="/main_folder/gvsoc-01/install/bin:$PATH"
ENTRYPOINT [ "/bin/bash" ]
